### PR TITLE
Allow dots in package names.

### LINKED ISSUE #9: Having dots in the package name.
Packages like `backbone.wreqr` and `backbone.babysitter` can't be retrieved by `//domain.com/packages/backbone.wreqr` or `//domain.com/packages/search/backbone.wreqr`

### PR DESCRIPTION
**Pull request by bweston92**
Packages such as `backbone.wreqr` and `backbone.babysitter` where 404ing fixes #9

### CODE REVIEW

**Comment by toranb** [comment]
Excellent find! Would you mind adding a quick test to show this broken / then fixed? Thanks !!!

**Comment by bweston92** [comment]
Python is not my strong point to add tests but if you add a package with the name `backbone.wreqr` and go-to the route it will fail, apply my PR and it will work. Sorry.

**Comment by toranb** [comment]
Fair enough- I wanted to use this as a way to remote pair / mentor some python, tdd, tmux and vim :)

Let me know if you are up for it some night next week

**Comment by bweston92** [comment]
Remote pair? If you're willing to teach me the best practices in Python that is great, I've followed you on Twitter.

**Comment by toranb** [comment]
Sounds like a plan! ping me via email to confirm the date/time

toranb at gmail

**Pull request merged**
