### PR TITLE
Feature/delete packages via delete

### LINKED ISSUE #11: Methods on a package.
The following methods are no achievable on the package. `/packages/:package-name`
- DELETE
- PUT
- PATCH

### PR DESCRIPTION
**Pull request by bweston92**
Closes #11 as this allows the `DELETE` method.

### CODE REVIEW

**Comment by toranb** [comment]
This works from the api side of things but how does the bower CLI actually execute this command? or does it even allow you to remove/delete a package yet? I ask because back when I wrote this "remove" was a very manual process

**Comment by bweston92** [comment]
I know there is annunregister but how it works I don't know. But this is standard rest so it should work. I would imagine there is some authentication behind it.

—

**Comment by toranb** [comment]
Fair point - we can add this but if it's not supported by the bower command line does it make sense?

**Comment by bweston92** [comment]
I will read the code in the bower package of anything needs updating I will amend.

—

**Comment by bweston92** [comment]
The un-register command isn't yet implemented. Also they authenticate using a access token to the GitHub api. This doesn't suit everyone's needs, any ideas on this? https://github.com/bower/bower/issues/120

**Pull request closed without merging**
